name: flutter_todos
description: A new Flutter application.

version: 2.0.3+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3+1
  
  path: ^1.8.1
  path_provider: ^2.0.11
  
  http: ^0.13.5
  flutter_slidable: any
  cloud_firestore: any
  provider: ^6.0.3


flutter:
  uses-material-design: true

